//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laba4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Good
    {
        public int id { get; set; }
        public string name { get; set; }
        public string desc { get; set; }
        public string category { get; set; }
        public Nullable<int> rate { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> amount { get; set; }
        public string other { get; set; }
        public byte[] picture { get; set; }
    
        public virtual Category Category1 { get; set; }
    }
}
